import React from 'react';
import { TouchableHighlight, Text, Alert, View } from 'react-native';
import RazorpayCheckout from 'react-native-razorpay';

const CheckoutScreen = ({ route, navigation }: any) => {
    // Destructure params passed from the previous screen
    const { totalAmount, orderId, customerName } = route.params;
    const [isProcessing, setIsProcessing] = React.useState(false);

    const handlePayment = () => {
        if (isProcessing) return; // Exit if already opening
        setIsProcessing(true);
        // Amount is in currency subunits. 
        // For INR, 5000 = ₹50.00 (Amount * 100)
        const options = {
            description: "Credits towards consultation",
            image: 'https://picsum.photos/id/1/200/300',
            currency: 'INR',
            key: 'rzp_test_SmqwhjEZRAizAi', // Replace with your actual Test Key
            //Test Key Secret: LkfeixGRNmJdmqVZN3t8RFJ2
            amount: Number(totalAmount),
            name: 'Your Business Name',
            order_id: '',//orderId, // MUST be generated by backend
            prefill: {
                email: 'user@example.com',
                contact: '919786970050',
                name: customerName
            },
            theme: { color: '#53a20e' }
        };

        RazorpayCheckout.open(options)
            .then((data: any) => {
                // handle success
                // data contains: razorpay_payment_id, razorpay_order_id, razorpay_signature
                Alert.alert("Payment Success", `ID: ${data.razorpay_payment_id}`);


                // CRITICAL: Send data.razorpay_payment_id to your backend 
                // to verify the signature before providing service.
            })
            .catch((error: any) => {
                console.log('payment error', error)
                //console.error("SDK Error Details:", JSON.stringify(error, null, 2));
                // handle failure
                // Alert.alert("Payment Failed", `Code: ${error.code} \nDescription: ${error.description}`);
            });
    };

    return (
        <View className="flex-1 items-center justify-center bg-white p-5">
            <TouchableHighlight
                onPress={handlePayment}
                underlayColor="#45870c"
                className="bg-[#53a20e] px-8 py-4 rounded-xl shadow-md"
            >
                <Text className="text-white font-bold text-lg">Pay Now ₹{totalAmount}</Text>
            </TouchableHighlight>
        </View>
    );
};

export default CheckoutScreen;